// This file is part of libnosync library. See LICENSE file for license details.
#ifndef NOSYNC__READER_WRITER_BYTES_IO_H
#define NOSYNC__READER_WRITER_BYTES_IO_H

#include <nosync/bytes-io.h>
#include <memory>


namespace nosync
{

/*!
Create bytes_io from separate bytes_reader and bytes_writer objects.

The generated bytes_io object will delegate all calls to the underlying reader
and writer.
*/
std::shared_ptr<bytes_io> make_reader_writer_bytes_io(
    std::shared_ptr<bytes_reader> reader, std::shared_ptr<bytes_writer> writer);

}

#endif /* NOSYNC__READER_WRITER_BYTES_IO_H */
